<?php
require_once("config-students.php");
?>
<?php
//  patient_id: patient_id,
//  patient_name: patient_name,
//  form_name: form_name,
//  creation_data : creation_data,
//  update_date : update_date,
//  nameSurname: nameSurname,
//  dob : dob,
//  gender: gender,
//  maritalStatus: maritalStatus,
//  profession: profession,
//  education: education,
//  protocol_file_no: protocol_file_no,
//  admissionDate: admissionDate,
//  department: department,
//  diagnosis: diagnosis,
//  doctorName: doctorName,
//  numberOfChildren: numberOfChildren,
//  socialSecurity: socialSecurity,
//  language: language,
//  translatorRequirement: translatorRequirement,
//  bloodType: bloodType,
//  transfusionStatus: transfusionStatus,
//  transfusionReaction: transfusionReaction,
//  infoStorageType: infoStorageType,
//  kolbandi: kolbandi,
//  relativeNameSurname: relativeNameSurname,
//  relativePhone: relativePhone,
//  relativeAddress: relativeAddress,
//  relativeDistance: relativeDistance,
//  previousHospitalization: previousHospitalization,
//  hospitalization_year: hospitalization_year,
//  hospitalization_location: hospitalization_location,
//  hospitalization_reason: hospitalization_reason,
//  diseases: diseases,
//  previousSurgeries: previousSurgeries,
//  accidents: accidents,
//  infectiousDisease: infectiousDisease,
//  allergies: allergies,
//  allergen: allergen,
//  allergySymptoms: allergySymptoms,
//  allergyTherapy: allergyTherapy,
//  previousMedications: previousMedications,
//  medicineName: medicineName,
//  medicineFrequency: medicineFrequency,
//  medicineDose: medicineDose,
//  intakeMethod: intakeMethod,
//  intakeTimes: intakeTimes,
//  aidTools: aidTools,
//  aidToolsDsc: aidToolsDsc,
//  smoking: smoking,
//  smokingAmount: smokingAmount,
//  smokingTime: smokingTime,
//  alcoholUsage: alcoholUsage,
//  alcoholAmount: alcoholAmount,
//  alcoholUsageTime: alcoholUsageTime,
//  teaUsage: teaUsage,
//  teaUsageAmount: teaUsageAmount,
//  teaUsageTime: teaUsageTime,
//  coffeeUsage: coffeeUsage,
//  coffeeUsageAmount: coffeeUsageAmount,
//  coffeeUsageTime: coffeeUsageTime,
//  otherHabits: otherHabits,
//  otherHabitsInput: otherHabitsInput,
//  otherHabitsAmount: otherHabitsAmount,
//  otherHabitsTime: otherHabitsTime,
//  familyIllnesses: familyIllnesses,
//  familyMemberRelation: familyMemberRelation,
//  familyMemberIllness: familyMemberIllness,
//  arrivalFrom: arrivalFrom,
//  hospitalArrivalMethod : hospitalArrivalMethod,
//  complaints: complaints,
//  medicalDiagnosis: medicalDiagnosis               



if (isset($_POST["patient_name"])) {

    if (isset($_POST['isUpdate'])) {

        $stmt = $db->prepare("UPDATE form3 SET 
                        update_date = ?,
                        nameSurname = ?,
                        dob = ?,
                        gender = ?,
                        maritalStatus = ?,
                        profession = ?,
                        education = ?,
                        protocol_file_no = ?,
                        admissionDate = ?,
                        department = ?,
                        diagnosis = ?,
                        doctorName = ?,
                        numberOfChildren = ?,
                        socialSecurity = ?,
                        language = ?,
                        translatorRequirement = ?,
                        bloodType = ?,
                        transfusionStatus = ?,
                        transfusionReaction = ?,
                        infoStorageType = ?,
                        kolbandi = ?,
                        relativeNameSurname = ?,
                        relativePhone = ?,
                        relativeAddress = ?,
                        relativeDistance = ?,
                        previousHospitalization = ?,
                        hospitalization_year = ?,
                        hospitalization_location = ?,
                        hospitalization_reason = ?,
                        diseases = ?,
                        previousSurgeries = ?,
                        accidents = ?,
                        infectiousDisease = ?,
                        allergies = ?,
                        allergen = ?,
                        allergySymptoms = ?,
                        allergyTherapy = ?,
                        previousMedications = ?,
                        medicineName = ?,
                        medicineFrequency = ?,
                        medicineDose = ?,
                        intakeMethod = ?,
                        intakeTimes = ?,
                        aidTools = ?,
                        aidToolsDsc = ?,
                        smoking = ?,
                        smokingAmount = ?,
                        smokingTime = ?,
                        alcoholUsage = ?,
                        alcoholAmount = ?,
                        alcoholUsageTime = ?,
                        teaUsage = ?,
                        teaUsageAmount = ?,
                        teaUsageTime = ?,
                        coffeeUsage = ?,
                        coffeeUsageAmount = ?,
                        coffeeUsageTime = ?,
                        otherHabits = ?,
                        otherHabitsInput = ?,
                        otherHabitsAmount = ?,
                        otherHabitsTime = ?,
                        familyIllnesses = ?,
                        familyMemberRelation = ?,
                        familyMemberIllness = ?,
                        arrivalFrom = ?,
                        hospitalArrivalMethod = ?,
                        complaints = ?,
                        medicalDiagnosis = ?
                        WHERE form_id = ?");

        $result =    $stmt->execute([
            $_POST["creation_date"],
            $_POST["nameSurname"],
            $_POST["dob"],
            $_POST["gender"],
            $_POST["maritalStatus"],
            $_POST["profession"],
            $_POST["education"],
            $_POST["protocol_file_no"],
            $_POST["admissionDate"],
            $_POST["department"],
            $_POST["diagnosis"],
            $_POST["doctorName"],
            $_POST["numberOfChildren"],
            $_POST["socialSecurity"],
            $_POST["language"],
            $_POST["translatorRequirement"],
            $_POST["bloodType"],
            $_POST["transfusionStatus"],
            $_POST["transfusionReaction"],
            $_POST["infoStorageType"],
            $_POST["kolbandi"],
            $_POST["relativeNameSurname"],
            $_POST["relativePhone"],
            $_POST["relativeAddress"],
            $_POST["relativeDistance"],
            $_POST["previousHospitalization"],
            $_POST["hospitalization_year"],
            $_POST["hospitalization_location"],
            $_POST["hospitalization_reason"],
            $_POST["diseases"],
            $_POST["previousSurgeries"],
            $_POST["accidents"],
            $_POST["infectiousDisease"],
            $_POST["allergies"],
            $_POST["allergen"],
            $_POST["allergySymptoms"],
            $_POST["allergyTherapy"],
            $_POST["previousMedications"],
            $_POST["medicineName"],
            $_POST["medicineFrequency"],
            $_POST["medicineDose"],
            $_POST["intakeMethod"],
            $_POST["intakeTimes"],
            $_POST["aidTools"],
            $_POST["aidToolsDsc"],
            $_POST["smoking"],
            $_POST["smokingAmount"],
            $_POST["smokingTime"],
            $_POST["alcoholUsage"],
            $_POST["alcoholAmount"],
            $_POST["alcoholUsageTime"],
            $_POST["teaUsage"],
            $_POST["teaUsageAmount"],
            $_POST["teaUsageTime"],
            $_POST["coffeeUsage"],
            $_POST["coffeeUsageAmount"],
            $_POST["coffeeUsageTime"],
            $_POST["otherHabits"],
            $_POST["otherHabitsInput"],
            $_POST["otherHabitsAmount"],
            $_POST["otherHabitsTime"],
            $_POST["familyIllnesses"],
            $_POST["familyMemberRelation"],
            $_POST["familyMemberIllness"],
            $_POST["arrivalFrom"],
            $_POST["hospitalArrivalMethod"],
            $_POST["complaints"],
            $_POST["medicalDiagnosis"],
            $_POST["form_id"]
        ]);


        if ($result) {
            echo "Güncelleme Başarılı!";
        } else {
            echo $result;
        }
    }

    $stmt = $db->prepare("INSERT into form3 (
                patient_name,
                patient_id,
                form_name,
                update_date,
                creation_date,
                nameSurname,
                dob,
                gender,
                maritalStatus,
                profession,
                education,
                protocol_file_no,
                admissionDate,
                department,
                diagnosis,
                doctorName,
                numberOfChildren,
                socialSecurity,
                language,
                translatorRequirement,
                bloodType,
                transfusionStatus,
                transfusionReaction,
                infoStorageType,
                kolbandi,
                relativeNameSurname,
                relativePhone,
                relativeAddress,
                relativeDistance,
                previousHospitalization,
                hospitalization_year,
                hospitalization_location,
                hospitalization_reason,
                diseases,
                previousSurgeries,
                accidents,
                infectiousDisease,
                allergies,
                allergen,
                allergySymptoms,
                allergyTherapy,
                previousMedications,
                medicineName,
                medicineFrequency,
                medicineDose,
                intakeMethod,
                intakeTimes,
                aidTools,
                aidToolsDsc,
                smoking,
                smokingAmount,
                smokingTime,
                alcoholUsage,
                alcoholAmount,
                alcoholUsageTime,
                teaUsage,
                teaUsageAmount,
                teaUsageTime,
                coffeeUsage,
                coffeeUsageAmount,
                coffeeUsageTime,
                otherHabits,
                otherHabitsInput,
                otherHabitsAmount,
                otherHabitsTime,
                familyIllnesses,
                familyMemberRelation,
                familyMemberIllness,
                arrivalFrom,
                hospitalArrivalMethod,
                complaints,
                medicalDiagnosis
                ) VALUES (?,?, ?, ?, ?, ? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");

    $result =   $stmt->execute([
        $_POST["patient_name"],
        $_POST["patient_id"],
        $_POST["form_num"],
        $_POST["creation_date"],
        $_POST["update_date"],
        $_POST["nameSurname"],
        $_POST["dob"],
        $_POST["gender"],
        $_POST["maritalStatus"],
        $_POST["profession"],
        $_POST["education"],
        $_POST["protocol_file_no"],
        $_POST["admissionDate"],
        $_POST["department"],
        $_POST["diagnosis"],
        $_POST["doctorName"],
        $_POST["numberOfChildren"],
        $_POST["socialSecurity"],
        $_POST["language"],
        $_POST["translatorRequirement"],
        $_POST["bloodType"],
        $_POST["transfusionStatus"],
        $_POST["transfusionReaction"],
        $_POST["infoStorageType"],
        $_POST["kolbandi"],
        $_POST["relativeNameSurname"],
        $_POST["relativePhone"],
        $_POST["relativeAddress"],
        $_POST["relativeDistance"],
        $_POST["previousHospitalization"],
        $_POST["hospitalization_year"],
        $_POST["hospitalization_location"],
        $_POST["hospitalization_reason"],
        $_POST["diseases"],
        $_POST["previousSurgeries"],
        $_POST["accidents"],
        $_POST["infectiousDisease"],
        $_POST["allergies"],
        $_POST["allergen"],
        $_POST["allergySymptoms"],
        $_POST["allergyTherapy"],
        $_POST["previousMedications"],
        $_POST["medicineName"],
        $_POST["medicineFrequency"],
        $_POST["medicineDose"],
        $_POST["intakeMethod"],
        $_POST["intakeTimes"],
        $_POST["aidTools"],
        $_POST["aidToolsDsc"],
        $_POST["smoking"],
        $_POST["smokingAmount"],
        $_POST["smokingTime"],
        $_POST["alcoholUsage"],
        $_POST["alcoholAmount"],
        $_POST["alcoholUsageTime"],
        $_POST["teaUsage"],
        $_POST["teaUsageAmount"],
        $_POST["teaUsageTime"],
        $_POST["coffeeUsage"],
        $_POST["coffeeUsageAmount"],
        $_POST["coffeeUsageTime"],
        $_POST["otherHabits"],
        $_POST["otherHabitsInput"],
        $_POST["otherHabitsAmount"],
        $_POST["otherHabitsTime"],
        $_POST["familyIllnesses"],
        $_POST["familyMemberRelation"],
        $_POST["familyMemberIllness"],
        $_POST["arrivalFrom"],
        $_POST["hospitalArrivalMethod"],
        $_POST["complaints"],
        $_POST["medicalDiagnosis"]        
    ]);


    if ($result) {
        echo "Ekleme Başarılı";
    } else {
        echo $result;
    }
} else {
    echo 'error';
}
?>