CREATE TABLE tani1 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani2 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani3 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani4 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani5 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani6 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani7 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani8 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani9 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani10 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani11 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani12 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani13 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani14 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani15 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani16 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani17 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani18 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani19 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani20 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani21 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani22 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani23 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani24 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani25 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani26 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani27 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani28 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani29 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani30 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani31 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani32 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani33 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani34 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani35 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani36 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani37 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani38 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani39 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani40 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani41 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani42 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani43 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani44 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani45 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani46 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani47 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani48 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
CREATE TABLE tani49 (
    tani_id INT(11) PRIMARY KEY AUTO_INCREMENT,
    patient_id INT(11),
    patient_name TEXT,
    creation_date DATE,
    update_date DATE,
    noc_indicator TEXT,
    noc_indicator_after TEXT,
    noc_indicator_2 TEXT,
    noc_indicator_after_2 TEXT,
    noc_indicator_3 TEXT,
    noc_indicator_after_3 TEXT,
    nurse_attempt TEXT,
    nurse_education TEXT,
    collaborative_apps TEXT,
    evaluation boolean,
    parent_id INT(11),
    root_id INT(11),
    standalone boolean,
    time time(0)
);
